version: '3.8'

services:
  redis-db:
    image: redis:latest
    environment:
      REDIS_DATABASES: 0
      REDIS_PORT: 6379
    volumes:
      - redis_data:/root/redis
    ports:
      - 6379:6379
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db


volumes:
  redis_data:
  mongo_data:
