# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: giveaway.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'giveaway.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0egiveaway.proto\x12\x08giveaway\"#\n\x0fGiveawayRequest\x12\x10\n\x08initData\x18\x01 \x01(\t\"%\n\rGiveawayReply\x12\x14\n\x0cjson_message\x18\x01 \x01(\t2\x9d\x01\n\x07Greeter\x12\x43\n\x0bGetGiveaway\x12\x19.giveaway.GiveawayRequest\x1a\x17.giveaway.GiveawayReply\"\x00\x12M\n\x15ParticipatingGiveaway\x12\x19.giveaway.GiveawayRequest\x1a\x17.giveaway.GiveawayReply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'giveaway_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GIVEAWAYREQUEST']._serialized_start=28
  _globals['_GIVEAWAYREQUEST']._serialized_end=63
  _globals['_GIVEAWAYREPLY']._serialized_start=65
  _globals['_GIVEAWAYREPLY']._serialized_end=102
  _globals['_GREETER']._serialized_start=105
  _globals['_GREETER']._serialized_end=262
# @@protoc_insertion_point(module_scope)
