name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  REGISTRY: cr.selcloud.ru
  IMAGE_NAME: ${{ github.event.repository.name }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: token
        password: ${{secrets.SELECTEL_TOKEN}}

    - uses: docker/build-push-action@master
      with:
        context: .
        push: true
        tags: ${{ env.REGISTRY }}/goldgiveaway/${{ env.IMAGE_NAME }}
